# YAML configuration file for chipseq-pipelines

user: arendeiro
email: arendeiro@cemm.oeaw.ac.at

paths:
    parent: /projects
    parenthtml: /public_html

url: http://www.biomedical-sequencing.at/bocklab/arendeiro/

sheet: # mandatory columns in sample annotation sheet
    - "cellLine"
    - "numberCells"
    - "technique"
    - "ip"
    - "patient"
    - "treatment"
    - "biologicalReplicate"
    - "technicalReplicate"
    - "unmappedBam"
    - "genome"

options:
    slurm:
        cpus: 4
        memorypercpu: 4000
        queue: shortq
        time: "10:00:00"
    mergetechnical: True
    mergebiological: True
    genomewindowwidth: 1000
    peakwindowwidth: 2000

genomes:
    - hg19
    - mm10

annotations:
    genomes:
        hg19: /fhgfs/prod/ngs_resources/genomes/hg19/forBowtie2/hg19/index_woRandom/hg19
        mm10: /fhgfs/prod/ngs_resources/genomes/mm10/forBowtie2/mm10/index_woRandom/mm10
    chrsizes:
        hg19: /fhgfs/groups/lab_bock/arendeiro/share/hg19.chrom.sizes
        mm10: /fhgfs/groups/lab_bock/arendeiro/share/mm10.chrom.sizes
    genomewindows:
        hg19: /fhgfs/groups/lab_bock/arendeiro/share/hg19.genomeWindows_1kb.bed
        mm10: /fhgfs/groups/lab_bock/arendeiro/share/mm10.genomeWindows_1kb.bed
    tss:
        hg19: /fhgfs/groups/lab_bock/arendeiro/share/GRCh37_hg19_refSeq.tss.bed
        mm10: /fhgfs/groups/lab_bock/arendeiro/share/GRCm38_mm19_refSeq.tss.bed

adapters: /fhgfs/groups/lab_bock/shared/cm.fa

tagment:
    - "DNASE"
    - "DNASESEQ"
    - "DNASE-SEQ"
    - "ATAC"
    - "ATAC-SEQ"
    - "ATACSEQ"
    - "CM"

histones:
    - "H2A"
    - "H2B"
    - "H3"
    - "H4"

broadfactors:
    - "H3K27ME1"
    - "H3K27ME2"
    - "H3K27ME3"
    - "H3K36ME1"
    - "H3K36ME2"
    - "H3K36ME3"
    - "H3K9ME1"
    - "H3K9ME2"
    - "H3K9ME3"
    - "H3K72ME1"
    - "H3K72ME2"
    - "H3K72ME3"

trackcolours:
    IGG: "153,153,153"  # grey
    INPUT: "153,153,153"
    H3K36ME1: "230,159,0"  # orange
    H3K36ME2: "230,159,0"
    H3K36ME3: "230,159,0"
    H3K4ME3: "0,158,115"  # bluish green
    H3K4ME1: "120,114,33"  # yellow
    H3K14ac: "120,114,33"
    H3K27ME1: "0,114,178"  # blue
    H3K27ME2: "0,114,178"
    H3K27ME3: "0,114,178"
    H3K9ME1: "86,180,233"  # sky blue
    H3K9ME2: "86,180,233"
    H3K9ME3: "86,180,233"
    H3AC: "213,94,0"  # vermillion
    H3K9AC: "213,94,0"
    H3K27AC: "213,94,0"
    H3K56AC: "213,94,0"
    H3K56AC: "213,94,0"
    H3K79ME1: "204,121,167"  # reddish purple
    H3K79ME2: "204,121,167"
    H3K79ME3: "204,121,167"
    ATAC: "0,158,115"
    DNASE: "0,158,115"

colourgradient: # 10 colour gradient from red to blue
    - "155,3,5"
    - "140,2,18"
    - "125,2,31"
    - "110,2,44"
    - "96,2,57"
    - "81,2,70"
    - "66,2,83"
    - "52,2,96"
    - "37,2,109"
    - "22,2,122"

